name: Run test suite on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{env.WORKLOAD_IDENDITY_PROVIDER}}
          service_account: ${{env.SERVICE_ACCOUNT}}
          
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pytest and check test coverage by the pytest-cov plugin
        run: pytest --cov=taskman -n auto
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
